services:
  predine_django:
    container_name: predinedjango
    build:
      context: .
    ports:
      - "8002:8000"
    restart: always
    command: /bin/sh -c "pip install -r requirements.txt && while sleep 1000; do :; done"
    depends_on:
      - predine_mysql
    volumes:
      - ../:/predine_backend

  predine_mysql:
    image: mysql:8
    container_name: predinemysql
    restart: always
    env_file:
      - ../env/mysql.env
    volumes:
      - ../db/:/var/lib/mysql
    ports:
      - 3303:3306

  predine_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: predinephp
    env_file:
      - ../env/phpmyadmin.env
    ports:
      - 5001:80
    restart: always
    depends_on:
      - predine_mysql
