BAD_REQUEST = 'Bad Request'
SUCCESS = 'Success'
LOGIN = 'Login Successfully!!'
UNAUTHENTICATED = 'Not Authenticated'
FORBIDDEN = 'Not Allowed'
WRONG_CREDENTIALS = 'Wrong Credentials'
OTP_SENT = 'OTP has been sent to your email!'
METHOD_NOT_ALLOWED = 'Method not Allowed'
VERIFY_EMAIL = 'Verified Successfully!'
OTP_INVALID = 'The OTP verification failed'
PASSWORD_NOT_MATCH = 'Password and confirm password should be same'
EMAIL_NOT_VERIFIED = 'Your Email is not Verified!'
REQUIRED = "is required field"
REGISTERED = "Registration successful!!"
NUMBER_INVALID = 'Invalid Phone Number'
EMAIL_INVALID = 'Invalid Email'
PASSWORD_CHECK = "Password must be at least 8 characters long and contain both letters and numbers (alphanumeric)"
EMAIL_ALREADY_VERIFIED = "Your emai has already verified, kindly go to login or continue the registration process."
INVALID_DATA = 'Invalid data has provided'
USER_ALREADY_REGISTERED = 'User has been already registered, kindly logged in!'
